Main Structure
ahmed-alfarouq/LeaderBoard pull request #1
Opened 2021-10-05 08:47 UTC by ahmed-al-farouq

What I did:
- Init webpack structure
- Add Style
- Add linters
- Add professional README file

2021-10-05 20:32 UTC, helman101 reviewed
# STATUS: INVALID 🔴⚠️ 

Hi @ahmed-al-farouq  😺 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not check for linter errors, your pull request should run a check for the following linters:
    ![image](https://user-images.githubusercontent.com/60789317/136097905-e0cbd860-f173-4a9a-ab2c-9cb1d4946079.png)
instead i only see this:
    ![imagen](https://user-images.githubusercontent.com/60789317/136098041-a6907894-458b-48a6-b4d7-1f0607aee24a.png)
Kindly check your linters set-up and send another review request when your linters look like those on the first image. 🚀 



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/CoND5j6Bn1QZUgm1xX/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-10-06 04:20 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your PR messages are descriptive ✔️

## Aspects to improve ♻️

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-06 04:21 UTC, vichuge requested changes

2021-10-06 04:21 UTC, vichuge commented on package.json
> +    "start": "webpack serve --open",
- [ ] Everything looks great, but I'm afraid I couldn't install the project locally...
- I clone the repo and select the structure branch
- I delete the `package-lock.json`
- I ran `npm i` and I have the next error:
![image](https://user-images.githubusercontent.com/20563252/136140073-1414168d-5824-470b-9e59-40f609a0ca10.png)
- For this same reason I couldn't use `npm start` (and this is a requirement for this project), please fix this bug. 🐶

2021-10-06 05:12 UTC, vichuge requested changes
# Required Changes ♻️ ♻️ ⚠️ ⚠️ 🚦 🚦 

Hi dear student, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.

![star_wars_almost_there](https://user-images.githubusercontent.com/20563252/121369354-644f4900-c901-11eb-9844-50c85d0f206b.gif)


## Aspects to improve ♻️
_Check the comments under the review._

- [ ] Check the comments under the review. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-06 05:12 UTC, vichuge commented on package.json
> +  },
- [ ] Please, to run the project locally, add the instruction to run `npm start` or `npm run start`, in this way I could be able to run the project locally on my computer. 🐶

2021-10-06 05:27 UTC, Lameck1 approved these changes
Hi, @ahmed-al-farouq,

Your project is complete!  It's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-06 05:28 UTC, merged